name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install npm packages
        run: npm install
      - name: Run Regression tests
        run: npm run cy:test
