name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install npm packages
        run: npm install
      - name: Run Regression tests
        uses: cypress-io/github-action@v2
        with:
          wait-on: "https://dev-mosaic-aks.np-mosaic-aks.shwaks.com"
